livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
podAntiAffinity:
  enabled: true

consoleLog:
  enabled: true
  logtype: console